# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b19295b845e0e1031a1160557fdab50df8033839d9653d9bc8be155187c9a16a10ad12fddfeabf1e705ed269975dcd81c69da3d8492bc9a061a56fa71b57b31

test:
  secret_key_base: 0a686677c500bde3fb6886bcca845e3a378bc36766205203b370f492fd736b87dff9a95555e976031cfce44fb85483812677cf0df34b517f325da1c1eed7292e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
